### ISSUE TITLE
Make sure Travis build is activated and working

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/ld4p-tracer-bullets#18]
We may need to make the repo public for this to work.

**Comment by darrenleeweber** [comment]
- Activated https://travis-ci.org/sul-dlss/ld4p-tracer-bullets
- Waiting for a build to be triggered to confirm it's working before closing this issue

**Comment by darrenleeweber** [comment]
It's now trying to build the project, but it's failing because travis.ci is not authorized to download the Oracle OJDBC maven artifact.

**Comment by darrenleeweber** [comment]
Closing this and moving remaining concerns to #31
