### ISSUE TITLE
org.jdom.jdom2 might be useful for RDF processing

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/ld4p-tracer-bullets#73]
This library was removed in #54 because it was not used anywhere (yet).  It might be useful later for RDF processing.

**Comment by darrenleeweber** [comment]
Some of the LOC marc2bibframe results do not refer to authority real-world-objects (RWO), e.g.
```rdf
<bf:Organization rdf:about="http://linked-data-test.stanford.edu/library/it 13004852organization15">
      <bf:authorizedAccessPoint>Petrie Museum of Egyptology--Catalogs.</bf:authorizedAccessPoint>
      <bf:label>Petrie Museum of Egyptology--Catalogs.</bf:label>
      <bf:hasAuthority rdf:resource="http://id.loc.gov/authorities/names/n50082486"/>
      <bf:hasAuthority rdf:resource="http://viaf.org/viaf/147720939"/>
</bf:Organization>
```
This organization has a RWO identifier, i.e.
- http://id.loc.gov/rwo/agents/n50082486.html
```rdf
<bf:Organization rdf about="http://id.loc.gov/rwo/agents/n50082486">
```

Part of our RDF processing needs to resolve these RWO identifiers.  
- this might be done with XQuery or with RDF tools
- the data might be resolved before or after it is submitted to our triple store

**Comment by jgreben** [comment]
Duplicates #14
